//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoFrame.Persistence.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHOTO_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHOTO_TABLE()
        {
            this.KEYWORD_TABLE = new HashSet<KEYWORD_TABLE>();
            this.ALBUM_TABLE = new HashSet<ALBUM_TABLE>();
        }
    
        public string FILEPATH { get; set; }
        public Nullable<bool> ISFAVORITE { get; set; }
        public string TAKEDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEYWORD_TABLE> KEYWORD_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALBUM_TABLE> ALBUM_TABLE { get; set; }
    }
}
