//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoFrame.Persistence.Repositories.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamBEntities : DbContext
    {
        public TeamBEntities()
            : base("name=TeamBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALBUM_TABLE> ALBUM_TABLE { get; set; }
        public virtual DbSet<KEYWORD_TABLE> KEYWORD_TABLE { get; set; }
        public virtual DbSet<PHOTO_TABLE> PHOTO_TABLE { get; set; }
    }
}
